name: Scrape and Publish

on:
  schedule:
    - cron: "0 8 * * *"   # run once a day at 8 AM UTC (adjust as needed)
  workflow_dispatch:       # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests pillow beautifulsoup4

      - name: Run scraper
        run: |
          python scraper.py

      - name: Commit results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add output/
          git commit -m "Update images" || echo "No changes"
          git push
